/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminId = bigint;
export interface AdminProfile {
  'id' : AdminId,
  'principal' : Principal,
  'secretKeyVerified' : boolean,
  'registeredAt' : Timestamp,
}
export interface AnalyticsSummary {
  'totalNGOs' : bigint,
  'inTransitRequests' : bigint,
  'totalUsers' : bigint,
  'deliveredRequests' : bigint,
  'claimedRequests' : bigint,
  'totalRequests' : bigint,
  'openRequests' : bigint,
}
export interface CreateRequestArgs {
  'urgency' : UrgencyLevel,
  'description' : [] | [string],
  'userLocation' : Location,
  'resourceType' : ResourceType,
  'quantity' : bigint,
}
export interface Inventory {
  'lastUpdated' : Timestamp,
  'resourceType' : ResourceType,
  'ngoId' : NGOId,
  'quantity' : bigint,
}
export interface Location { 'lat' : number, 'lng' : number }
export type NGOId = bigint;
export interface NGOProfile {
  'id' : NGOId,
  'principal' : Principal,
  'orgName' : string,
  'serviceRadius' : number,
  'registeredAt' : Timestamp,
  'location' : Location,
  'contactPhone' : string,
}
export interface RegisterAdminArgs { 'secretKey' : string }
export interface RegisterNGOArgs {
  'orgName' : string,
  'serviceRadius' : number,
  'location' : Location,
  'contactPhone' : string,
}
export interface RegisterUserArgs {
  'name' : string,
  'aadhaarDeclared' : boolean,
  'panDeclared' : boolean,
  'phone' : string,
  'location' : Location,
}
export interface ReliefRequest {
  'id' : RequestId,
  'status' : RequestStatus,
  'deliveredAt' : [] | [Timestamp],
  'urgency' : UrgencyLevel,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'claimedAt' : [] | [Timestamp],
  'claimedBy' : [] | [NGOId],
  'userLocation' : Location,
  'resourceType' : ResourceType,
  'quantity' : bigint,
}
export type RequestId = bigint;
export type RequestStatus = { 'open' : null } |
  { 'claimed' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null };
export type ResourceType = { 'other' : null } |
  { 'food' : null } |
  { 'water' : null } |
  { 'medical' : null };
export type Timestamp = bigint;
export interface UpdateInventoryArgs {
  'resourceType' : ResourceType,
  'delta' : bigint,
  'reason' : string,
}
export interface UpdateRequestStatusArgs {
  'status' : RequestStatus,
  'requestId' : RequestId,
}
export type UrgencyLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type UserId = bigint;
export interface UserProfile {
  'id' : UserId,
  'principal' : Principal,
  'name' : string,
  'aadhaarDeclared' : boolean,
  'panDeclared' : boolean,
  'phone' : string,
  'registeredAt' : Timestamp,
  'location' : Location,
}
export interface VerificationCounts {
  'aadhaarDeclared' : bigint,
  'bothDeclared' : bigint,
  'panDeclared' : bigint,
  'totalUsers' : bigint,
}
export interface _SERVICE {
  'askAI' : ActorMethod<[string], string>,
  'claimRequest' : ActorMethod<[RequestId], boolean>,
  'createRequest' : ActorMethod<[CreateRequestArgs], ReliefRequest>,
  'generateOTP' : ActorMethod<[string], string>,
  'getAllNGOs' : ActorMethod<[], Array<NGOProfile>>,
  'getAllRequestsForAdmin' : ActorMethod<[], Array<ReliefRequest>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getMyAdminProfile' : ActorMethod<[], [] | [AdminProfile]>,
  'getMyNGOProfile' : ActorMethod<[], [] | [NGOProfile]>,
  'getMyUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getNGOInventory' : ActorMethod<[NGOId], Array<Inventory>>,
  'getNGOProfile' : ActorMethod<[NGOId], [] | [NGOProfile]>,
  'getNearbyNGOs' : ActorMethod<[Location, number], Array<NGOProfile>>,
  'getOpenRequests' : ActorMethod<[], Array<ReliefRequest>>,
  'getRequestsByNGO' : ActorMethod<[NGOId], Array<ReliefRequest>>,
  'getRequestsByUser' : ActorMethod<[UserId], Array<ReliefRequest>>,
  'getStatus' : ActorMethod<
    [],
    { 'alive' : boolean, 'version' : string, 'timestamp' : bigint }
  >,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getVerificationCounts' : ActorMethod<[], VerificationCounts>,
  'loginAdmin' : ActorMethod<
    [string],
    { 'ok' : AdminProfile } |
      { 'err' : string }
  >,
  'loginNGO' : ActorMethod<
    [string, string],
    { 'ok' : NGOProfile } |
      { 'err' : string }
  >,
  'loginUser' : ActorMethod<
    [string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'registerAdmin' : ActorMethod<
    [RegisterAdminArgs],
    { 'ok' : AdminProfile } |
      { 'err' : string }
  >,
  'registerNGO' : ActorMethod<
    [RegisterNGOArgs],
    { 'ok' : NGOProfile } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [RegisterUserArgs],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'updateInventory' : ActorMethod<[UpdateInventoryArgs], Inventory>,
  'updateRequestStatus' : ActorMethod<[UpdateRequestStatusArgs], boolean>,
  'verifyOTP' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];