/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RequestId = IDL.Nat;
export const UrgencyLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const ResourceType = IDL.Variant({
  'other' : IDL.Null,
  'food' : IDL.Null,
  'water' : IDL.Null,
  'medical' : IDL.Null,
});
export const CreateRequestArgs = IDL.Record({
  'urgency' : UrgencyLevel,
  'description' : IDL.Opt(IDL.Text),
  'userLocation' : Location,
  'resourceType' : ResourceType,
  'quantity' : IDL.Nat,
});
export const RequestStatus = IDL.Variant({
  'open' : IDL.Null,
  'claimed' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Nat;
export const NGOId = IDL.Nat;
export const ReliefRequest = IDL.Record({
  'id' : RequestId,
  'status' : RequestStatus,
  'deliveredAt' : IDL.Opt(Timestamp),
  'urgency' : UrgencyLevel,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'claimedAt' : IDL.Opt(Timestamp),
  'claimedBy' : IDL.Opt(NGOId),
  'userLocation' : Location,
  'resourceType' : ResourceType,
  'quantity' : IDL.Nat,
});
export const NGOProfile = IDL.Record({
  'id' : NGOId,
  'principal' : IDL.Principal,
  'orgName' : IDL.Text,
  'serviceRadius' : IDL.Float64,
  'registeredAt' : Timestamp,
  'location' : Location,
  'contactPhone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'aadhaarDeclared' : IDL.Bool,
  'panDeclared' : IDL.Bool,
  'phone' : IDL.Text,
  'registeredAt' : Timestamp,
  'location' : Location,
});
export const AnalyticsSummary = IDL.Record({
  'totalNGOs' : IDL.Nat,
  'inTransitRequests' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'deliveredRequests' : IDL.Nat,
  'claimedRequests' : IDL.Nat,
  'totalRequests' : IDL.Nat,
  'openRequests' : IDL.Nat,
});
export const AdminId = IDL.Nat;
export const AdminProfile = IDL.Record({
  'id' : AdminId,
  'principal' : IDL.Principal,
  'secretKeyVerified' : IDL.Bool,
  'registeredAt' : Timestamp,
});
export const Inventory = IDL.Record({
  'lastUpdated' : Timestamp,
  'resourceType' : ResourceType,
  'ngoId' : NGOId,
  'quantity' : IDL.Nat,
});
export const VerificationCounts = IDL.Record({
  'aadhaarDeclared' : IDL.Nat,
  'bothDeclared' : IDL.Nat,
  'panDeclared' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const RegisterAdminArgs = IDL.Record({ 'secretKey' : IDL.Text });
export const RegisterNGOArgs = IDL.Record({
  'orgName' : IDL.Text,
  'serviceRadius' : IDL.Float64,
  'location' : Location,
  'contactPhone' : IDL.Text,
});
export const RegisterUserArgs = IDL.Record({
  'name' : IDL.Text,
  'aadhaarDeclared' : IDL.Bool,
  'panDeclared' : IDL.Bool,
  'phone' : IDL.Text,
  'location' : Location,
});
export const UpdateInventoryArgs = IDL.Record({
  'resourceType' : ResourceType,
  'delta' : IDL.Int,
  'reason' : IDL.Text,
});
export const UpdateRequestStatusArgs = IDL.Record({
  'status' : RequestStatus,
  'requestId' : RequestId,
});

export const idlService = IDL.Service({
  'askAI' : IDL.Func([IDL.Text], [IDL.Text], []),
  'claimRequest' : IDL.Func([RequestId], [IDL.Bool], []),
  'createRequest' : IDL.Func([CreateRequestArgs], [ReliefRequest], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllNGOs' : IDL.Func([], [IDL.Vec(NGOProfile)], ['query']),
  'getAllRequestsForAdmin' : IDL.Func([], [IDL.Vec(ReliefRequest)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getMyAdminProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
  'getMyNGOProfile' : IDL.Func([], [IDL.Opt(NGOProfile)], ['query']),
  'getMyUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getNGOInventory' : IDL.Func([NGOId], [IDL.Vec(Inventory)], ['query']),
  'getNGOProfile' : IDL.Func([NGOId], [IDL.Opt(NGOProfile)], ['query']),
  'getNearbyNGOs' : IDL.Func(
      [Location, IDL.Float64],
      [IDL.Vec(NGOProfile)],
      ['query'],
    ),
  'getOpenRequests' : IDL.Func([], [IDL.Vec(ReliefRequest)], ['query']),
  'getRequestsByNGO' : IDL.Func([NGOId], [IDL.Vec(ReliefRequest)], ['query']),
  'getRequestsByUser' : IDL.Func([UserId], [IDL.Vec(ReliefRequest)], ['query']),
  'getStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'alive' : IDL.Bool,
          'version' : IDL.Text,
          'timestamp' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getVerificationCounts' : IDL.Func([], [VerificationCounts], ['query']),
  'loginAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : AdminProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'loginNGO' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : NGOProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'loginUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'registerAdmin' : IDL.Func(
      [RegisterAdminArgs],
      [IDL.Variant({ 'ok' : AdminProfile, 'err' : IDL.Text })],
      [],
    ),
  'registerNGO' : IDL.Func(
      [RegisterNGOArgs],
      [IDL.Variant({ 'ok' : NGOProfile, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [RegisterUserArgs],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'updateInventory' : IDL.Func([UpdateInventoryArgs], [Inventory], []),
  'updateRequestStatus' : IDL.Func([UpdateRequestStatusArgs], [IDL.Bool], []),
  'verifyOTP' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RequestId = IDL.Nat;
  const UrgencyLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Location = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const ResourceType = IDL.Variant({
    'other' : IDL.Null,
    'food' : IDL.Null,
    'water' : IDL.Null,
    'medical' : IDL.Null,
  });
  const CreateRequestArgs = IDL.Record({
    'urgency' : UrgencyLevel,
    'description' : IDL.Opt(IDL.Text),
    'userLocation' : Location,
    'resourceType' : ResourceType,
    'quantity' : IDL.Nat,
  });
  const RequestStatus = IDL.Variant({
    'open' : IDL.Null,
    'claimed' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Nat;
  const NGOId = IDL.Nat;
  const ReliefRequest = IDL.Record({
    'id' : RequestId,
    'status' : RequestStatus,
    'deliveredAt' : IDL.Opt(Timestamp),
    'urgency' : UrgencyLevel,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'claimedAt' : IDL.Opt(Timestamp),
    'claimedBy' : IDL.Opt(NGOId),
    'userLocation' : Location,
    'resourceType' : ResourceType,
    'quantity' : IDL.Nat,
  });
  const NGOProfile = IDL.Record({
    'id' : NGOId,
    'principal' : IDL.Principal,
    'orgName' : IDL.Text,
    'serviceRadius' : IDL.Float64,
    'registeredAt' : Timestamp,
    'location' : Location,
    'contactPhone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'aadhaarDeclared' : IDL.Bool,
    'panDeclared' : IDL.Bool,
    'phone' : IDL.Text,
    'registeredAt' : Timestamp,
    'location' : Location,
  });
  const AnalyticsSummary = IDL.Record({
    'totalNGOs' : IDL.Nat,
    'inTransitRequests' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'deliveredRequests' : IDL.Nat,
    'claimedRequests' : IDL.Nat,
    'totalRequests' : IDL.Nat,
    'openRequests' : IDL.Nat,
  });
  const AdminId = IDL.Nat;
  const AdminProfile = IDL.Record({
    'id' : AdminId,
    'principal' : IDL.Principal,
    'secretKeyVerified' : IDL.Bool,
    'registeredAt' : Timestamp,
  });
  const Inventory = IDL.Record({
    'lastUpdated' : Timestamp,
    'resourceType' : ResourceType,
    'ngoId' : NGOId,
    'quantity' : IDL.Nat,
  });
  const VerificationCounts = IDL.Record({
    'aadhaarDeclared' : IDL.Nat,
    'bothDeclared' : IDL.Nat,
    'panDeclared' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const RegisterAdminArgs = IDL.Record({ 'secretKey' : IDL.Text });
  const RegisterNGOArgs = IDL.Record({
    'orgName' : IDL.Text,
    'serviceRadius' : IDL.Float64,
    'location' : Location,
    'contactPhone' : IDL.Text,
  });
  const RegisterUserArgs = IDL.Record({
    'name' : IDL.Text,
    'aadhaarDeclared' : IDL.Bool,
    'panDeclared' : IDL.Bool,
    'phone' : IDL.Text,
    'location' : Location,
  });
  const UpdateInventoryArgs = IDL.Record({
    'resourceType' : ResourceType,
    'delta' : IDL.Int,
    'reason' : IDL.Text,
  });
  const UpdateRequestStatusArgs = IDL.Record({
    'status' : RequestStatus,
    'requestId' : RequestId,
  });
  
  return IDL.Service({
    'askAI' : IDL.Func([IDL.Text], [IDL.Text], []),
    'claimRequest' : IDL.Func([RequestId], [IDL.Bool], []),
    'createRequest' : IDL.Func([CreateRequestArgs], [ReliefRequest], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllNGOs' : IDL.Func([], [IDL.Vec(NGOProfile)], ['query']),
    'getAllRequestsForAdmin' : IDL.Func(
        [],
        [IDL.Vec(ReliefRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getMyAdminProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
    'getMyNGOProfile' : IDL.Func([], [IDL.Opt(NGOProfile)], ['query']),
    'getMyUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getNGOInventory' : IDL.Func([NGOId], [IDL.Vec(Inventory)], ['query']),
    'getNGOProfile' : IDL.Func([NGOId], [IDL.Opt(NGOProfile)], ['query']),
    'getNearbyNGOs' : IDL.Func(
        [Location, IDL.Float64],
        [IDL.Vec(NGOProfile)],
        ['query'],
      ),
    'getOpenRequests' : IDL.Func([], [IDL.Vec(ReliefRequest)], ['query']),
    'getRequestsByNGO' : IDL.Func([NGOId], [IDL.Vec(ReliefRequest)], ['query']),
    'getRequestsByUser' : IDL.Func(
        [UserId],
        [IDL.Vec(ReliefRequest)],
        ['query'],
      ),
    'getStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'alive' : IDL.Bool,
            'version' : IDL.Text,
            'timestamp' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getVerificationCounts' : IDL.Func([], [VerificationCounts], ['query']),
    'loginAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : AdminProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'loginNGO' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : NGOProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'loginUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'registerAdmin' : IDL.Func(
        [RegisterAdminArgs],
        [IDL.Variant({ 'ok' : AdminProfile, 'err' : IDL.Text })],
        [],
      ),
    'registerNGO' : IDL.Func(
        [RegisterNGOArgs],
        [IDL.Variant({ 'ok' : NGOProfile, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [RegisterUserArgs],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'updateInventory' : IDL.Func([UpdateInventoryArgs], [Inventory], []),
    'updateRequestStatus' : IDL.Func([UpdateRequestStatusArgs], [IDL.Bool], []),
    'verifyOTP' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };