/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
}
export type Timestamp = bigint;
export interface VerificationCounts {
    aadhaarDeclared: bigint;
    bothDeclared: bigint;
    panDeclared: bigint;
    totalUsers: bigint;
}
export interface UpdateRequestStatusArgs {
    status: RequestStatus;
    requestId: RequestId;
}
export interface UpdateInventoryArgs {
    resourceType: ResourceType;
    delta: bigint;
    reason: string;
}
export interface ReliefRequest {
    id: RequestId;
    status: RequestStatus;
    deliveredAt?: Timestamp;
    urgency: UrgencyLevel;
    userId: UserId;
    createdAt: Timestamp;
    description?: string;
    claimedAt?: Timestamp;
    claimedBy?: NGOId;
    userLocation: Location;
    resourceType: ResourceType;
    quantity: bigint;
}
export interface RegisterUserArgs {
    name: string;
    aadhaarDeclared: boolean;
    panDeclared: boolean;
    phone: string;
    location: Location;
}
export interface RegisterAdminArgs {
    secretKey: string;
}
export interface NGOProfile {
    id: NGOId;
    principal: Principal;
    orgName: string;
    serviceRadius: number;
    registeredAt: Timestamp;
    location: Location;
    contactPhone: string;
}
export type NGOId = bigint;
export interface Inventory {
    lastUpdated: Timestamp;
    resourceType: ResourceType;
    ngoId: NGOId;
    quantity: bigint;
}
export interface AnalyticsSummary {
    totalNGOs: bigint;
    inTransitRequests: bigint;
    totalUsers: bigint;
    deliveredRequests: bigint;
    claimedRequests: bigint;
    totalRequests: bigint;
    openRequests: bigint;
}
export interface CreateRequestArgs {
    urgency: UrgencyLevel;
    description?: string;
    userLocation: Location;
    resourceType: ResourceType;
    quantity: bigint;
}
export type UserId = bigint;
export interface RegisterNGOArgs {
    orgName: string;
    serviceRadius: number;
    location: Location;
    contactPhone: string;
}
export interface AdminProfile {
    id: AdminId;
    principal: Principal;
    secretKeyVerified: boolean;
    registeredAt: Timestamp;
}
export type RequestId = bigint;
export interface UserProfile {
    id: UserId;
    principal: Principal;
    name: string;
    aadhaarDeclared: boolean;
    panDeclared: boolean;
    phone: string;
    registeredAt: Timestamp;
    location: Location;
}
export type AdminId = bigint;
export enum RequestStatus {
    open = "open",
    claimed = "claimed",
    inTransit = "inTransit",
    delivered = "delivered"
}
export enum ResourceType {
    other = "other",
    food = "food",
    water = "water",
    medical = "medical"
}
export enum UrgencyLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    askAI(userMessage: string): Promise<string>;
    claimRequest(requestId: RequestId): Promise<boolean>;
    createRequest(args: CreateRequestArgs): Promise<ReliefRequest>;
    generateOTP(_email: string): Promise<string>;
    getAllNGOs(): Promise<Array<NGOProfile>>;
    getAllRequestsForAdmin(): Promise<Array<ReliefRequest>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAnalyticsSummary(): Promise<AnalyticsSummary>;
    getMyAdminProfile(): Promise<AdminProfile | null>;
    getMyNGOProfile(): Promise<NGOProfile | null>;
    getMyUserProfile(): Promise<UserProfile | null>;
    getNGOInventory(ngoId: NGOId): Promise<Array<Inventory>>;
    getNGOProfile(id: NGOId): Promise<NGOProfile | null>;
    getNearbyNGOs(location: Location, radiusKm: number): Promise<Array<NGOProfile>>;
    getOpenRequests(): Promise<Array<ReliefRequest>>;
    getRequestsByNGO(ngoId: NGOId): Promise<Array<ReliefRequest>>;
    getRequestsByUser(userId: UserId): Promise<Array<ReliefRequest>>;
    getStatus(): Promise<{
        alive: boolean;
        version: string;
        timestamp: bigint;
    }>;
    getUserProfile(id: UserId): Promise<UserProfile | null>;
    getVerificationCounts(): Promise<VerificationCounts>;
    loginAdmin(secretKey: string): Promise<{
        __kind__: "ok";
        ok: AdminProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    loginNGO(orgName: string, contactPhone: string): Promise<{
        __kind__: "ok";
        ok: NGOProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    loginUser(phone: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerAdmin(args: RegisterAdminArgs): Promise<{
        __kind__: "ok";
        ok: AdminProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerNGO(args: RegisterNGOArgs): Promise<{
        __kind__: "ok";
        ok: NGOProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(args: RegisterUserArgs): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateInventory(args: UpdateInventoryArgs): Promise<Inventory>;
    updateRequestStatus(args: UpdateRequestStatusArgs): Promise<boolean>;
    verifyOTP(otp: string): Promise<boolean>;
}
import type { AdminProfile as _AdminProfile, CreateRequestArgs as _CreateRequestArgs, Inventory as _Inventory, Location as _Location, NGOId as _NGOId, NGOProfile as _NGOProfile, ReliefRequest as _ReliefRequest, RequestId as _RequestId, RequestStatus as _RequestStatus, ResourceType as _ResourceType, Timestamp as _Timestamp, UpdateInventoryArgs as _UpdateInventoryArgs, UpdateRequestStatusArgs as _UpdateRequestStatusArgs, UrgencyLevel as _UrgencyLevel, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async askAI(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askAI(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askAI(arg0);
            return result;
        }
    }
    async claimRequest(arg0: RequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimRequest(arg0);
            return result;
        }
    }
    async createRequest(arg0: CreateRequestArgs): Promise<ReliefRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createRequest(to_candid_CreateRequestArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ReliefRequest_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRequest(to_candid_CreateRequestArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ReliefRequest_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateOTP(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOTP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOTP(arg0);
            return result;
        }
    }
    async getAllNGOs(): Promise<Array<NGOProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNGOs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNGOs();
            return result;
        }
    }
    async getAllRequestsForAdmin(): Promise<Array<ReliefRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequestsForAdmin();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequestsForAdmin();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAnalyticsSummary(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getMyAdminProfile(): Promise<AdminProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAdminProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAdminProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNGOProfile(): Promise<NGOProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNGOProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNGOProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNGOInventory(arg0: NGOId): Promise<Array<Inventory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNGOInventory(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNGOInventory(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNGOProfile(arg0: NGOId): Promise<NGOProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNGOProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNGOProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbyNGOs(arg0: Location, arg1: number): Promise<Array<NGOProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyNGOs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyNGOs(arg0, arg1);
            return result;
        }
    }
    async getOpenRequests(): Promise<Array<ReliefRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenRequests();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenRequests();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsByNGO(arg0: NGOId): Promise<Array<ReliefRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsByNGO(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsByNGO(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsByUser(arg0: UserId): Promise<Array<ReliefRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsByUser(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsByUser(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatus(): Promise<{
        alive: boolean;
        version: string;
        timestamp: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatus();
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerificationCounts(): Promise<VerificationCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerificationCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerificationCounts();
            return result;
        }
    }
    async loginAdmin(arg0: string): Promise<{
        __kind__: "ok";
        ok: AdminProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginAdmin(arg0);
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginAdmin(arg0);
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginNGO(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: NGOProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginNGO(arg0, arg1);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginNGO(arg0, arg1);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAdmin(arg0: RegisterAdminArgs): Promise<{
        __kind__: "ok";
        ok: AdminProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAdmin(arg0);
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAdmin(arg0);
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerNGO(arg0: RegisterNGOArgs): Promise<{
        __kind__: "ok";
        ok: NGOProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNGO(arg0);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNGO(arg0);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterUserArgs): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInventory(arg0: UpdateInventoryArgs): Promise<Inventory> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventory(to_candid_UpdateInventoryArgs_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Inventory_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventory(to_candid_UpdateInventoryArgs_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Inventory_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRequestStatus(arg0: UpdateRequestStatusArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(to_candid_UpdateRequestStatusArgs_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(to_candid_UpdateRequestStatusArgs_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyOTP(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOTP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOTP(arg0);
            return result;
        }
    }
}
function from_candid_Inventory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inventory): Inventory {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ReliefRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReliefRequest): ReliefRequest {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UrgencyLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UrgencyLevel): UrgencyLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NGOId]): NGOId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminProfile]): AdminProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NGOProfile]): NGOProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastUpdated: _Timestamp;
    resourceType: _ResourceType;
    ngoId: _NGOId;
    quantity: bigint;
}): {
    lastUpdated: Timestamp;
    resourceType: ResourceType;
    ngoId: NGOId;
    quantity: bigint;
} {
    return {
        lastUpdated: value.lastUpdated,
        resourceType: from_candid_ResourceType_n16(_uploadFile, _downloadFile, value.resourceType),
        ngoId: value.ngoId,
        quantity: value.quantity
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RequestId;
    status: _RequestStatus;
    deliveredAt: [] | [_Timestamp];
    urgency: _UrgencyLevel;
    userId: _UserId;
    createdAt: _Timestamp;
    description: [] | [string];
    claimedAt: [] | [_Timestamp];
    claimedBy: [] | [_NGOId];
    userLocation: _Location;
    resourceType: _ResourceType;
    quantity: bigint;
}): {
    id: RequestId;
    status: RequestStatus;
    deliveredAt?: Timestamp;
    urgency: UrgencyLevel;
    userId: UserId;
    createdAt: Timestamp;
    description?: string;
    claimedAt?: Timestamp;
    claimedBy?: NGOId;
    userLocation: Location;
    resourceType: ResourceType;
    quantity: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n9(_uploadFile, _downloadFile, value.status),
        deliveredAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.deliveredAt)),
        urgency: from_candid_UrgencyLevel_n12(_uploadFile, _downloadFile, value.urgency),
        userId: value.userId,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.description)),
        claimedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.claimedAt)),
        claimedBy: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.claimedBy)),
        userLocation: value.userLocation,
        resourceType: from_candid_ResourceType_n16(_uploadFile, _downloadFile, value.resourceType),
        quantity: value.quantity
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    claimed: null;
} | {
    inTransit: null;
} | {
    delivered: null;
}): RequestStatus {
    return "open" in value ? RequestStatus.open : "claimed" in value ? RequestStatus.claimed : "inTransit" in value ? RequestStatus.inTransit : "delivered" in value ? RequestStatus.delivered : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): UrgencyLevel {
    return "low" in value ? UrgencyLevel.low : "high" in value ? UrgencyLevel.high : "medium" in value ? UrgencyLevel.medium : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    food: null;
} | {
    water: null;
} | {
    medical: null;
}): ResourceType {
    return "other" in value ? ResourceType.other : "food" in value ? ResourceType.food : "water" in value ? ResourceType.water : "medical" in value ? ResourceType.medical : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _NGOProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: NGOProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReliefRequest>): Array<ReliefRequest> {
    return value.map((x)=>from_candid_ReliefRequest_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inventory>): Array<Inventory> {
    return value.map((x)=>from_candid_Inventory_n23(_uploadFile, _downloadFile, x));
}
function to_candid_CreateRequestArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRequestArgs): _CreateRequestArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RequestStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): _ResourceType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInventoryArgs_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInventoryArgs): _UpdateInventoryArgs {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateRequestStatusArgs_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateRequestStatusArgs): _UpdateRequestStatusArgs {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UrgencyLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): _UrgencyLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urgency: UrgencyLevel;
    description?: string;
    userLocation: Location;
    resourceType: ResourceType;
    quantity: bigint;
}): {
    urgency: _UrgencyLevel;
    description: [] | [string];
    userLocation: _Location;
    resourceType: _ResourceType;
    quantity: bigint;
} {
    return {
        urgency: to_candid_UrgencyLevel_n3(_uploadFile, _downloadFile, value.urgency),
        description: value.description ? candid_some(value.description) : candid_none(),
        userLocation: value.userLocation,
        resourceType: to_candid_ResourceType_n5(_uploadFile, _downloadFile, value.resourceType),
        quantity: value.quantity
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resourceType: ResourceType;
    delta: bigint;
    reason: string;
}): {
    resourceType: _ResourceType;
    delta: bigint;
    reason: string;
} {
    return {
        resourceType: to_candid_ResourceType_n5(_uploadFile, _downloadFile, value.resourceType),
        delta: value.delta,
        reason: value.reason
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: RequestStatus;
    requestId: RequestId;
}): {
    status: _RequestStatus;
    requestId: _RequestId;
} {
    return {
        status: to_candid_RequestStatus_n32(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    open: null;
} | {
    claimed: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} {
    return value == RequestStatus.open ? {
        open: null
    } : value == RequestStatus.claimed ? {
        claimed: null
    } : value == RequestStatus.inTransit ? {
        inTransit: null
    } : value == RequestStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == UrgencyLevel.low ? {
        low: null
    } : value == UrgencyLevel.high ? {
        high: null
    } : value == UrgencyLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): {
    other: null;
} | {
    food: null;
} | {
    water: null;
} | {
    medical: null;
} {
    return value == ResourceType.other ? {
        other: null
    } : value == ResourceType.food ? {
        food: null
    } : value == ResourceType.water ? {
        water: null
    } : value == ResourceType.medical ? {
        medical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
